#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <cstdint>
#include <cstring>

#define THORQ_VERSION_APP_MAJOR 0
#define THORQ_VERSION_APP_MINOR 1
#define THORQ_VERSION_APP_PATCH 0

#define THORQ_VERSION_LNK_MAJOR 0
#define THORQ_VERSION_LNK_MINOR 1
#define THORQ_VERSION_LNK_PATCH 0

#define THORQ_CRYPTO_IV_LENGTH   24
#define THORQ_CRYPTO_KEY_LENGTH  32
#define THORQ_CRYPTO_EC_OID_NAME "secp256r1"
#define THORQ_CRYPTO_CIPHER_NAME "ChaCha(20)"
#define THORQ_CRYPTO_KEY_DERIVATION_FUNCTION "KDF2(SHA-256)"

#endif // CONSTANTS_H
