#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <cstdint>
#include <cstring>

#define THORQ_VERSION_SERVER_MAJOR 0
#define THORQ_VERSION_SERVER_MINOR 1
#define THORQ_VERSION_SERVER_PATCH 0

#define THORQ_VERSION_CLIENT_MAJOR 0
#define THORQ_VERSION_CLIENT_MINOR 1
#define THORQ_VERSION_CLIENT_PATCH 0

#define THORQ_VERSION_LINK_MAJOR 0
#define THORQ_VERSION_LINK_MINOR 1
#define THORQ_VERSION_LINK_PATCH 0

#define THORQ_CRYPTO_EC_ID "secp256r1"
#define THORQ_CRYPTO_CIPHER_IV_LEN 24
#define THORQ_CRYPTO_CIPHER_NAME   "ChaCha(20)"
#define THORQ_CRYPTO_KEY_LENGTH  32
#define THORQ_CRYPTO_KEY_DVFUNC "KDF2(SHA-256)"

#define THORQ_MSG_MAX_PAYLOAD_LEN 255 ///< Maximum payload length

#include "thorq_message_version.h"

constexpr thorq_version_t CurrentClientVersion
{
	THORQ_VERSION_CLIENT_MAJOR,
	THORQ_VERSION_CLIENT_MINOR,
	THORQ_VERSION_CLIENT_PATCH
};
constexpr thorq_version_t CurrentServerVersion
{
	THORQ_VERSION_SERVER_MAJOR,
	THORQ_VERSION_SERVER_MINOR,
	THORQ_VERSION_SERVER_PATCH
};
constexpr thorq_version_t CurrentLinkVersion
{
	THORQ_VERSION_LINK_MAJOR,
	THORQ_VERSION_LINK_MINOR,
	THORQ_VERSION_LINK_PATCH
};

#endif // CONSTANTS_H
