#ifndef THORQ_PAYLOAD_RELATION_H
#define THORQ_PAYLOAD_RELATION_H

/// @enum THORQ_PAYLOAD_FRIEND
enum THORQ_PAYLOAD_FRIEND : std::uint8_t
{
    THORQ_PAYLOAD_FRIEND_REQUEST,
    THORQ_PAYLOAD_FRIEND_ACCEPT,
    THORQ_PAYLOAD_FRIEND_DENY,
    THORQ_PAYLOAD_FRIEND_GETLIST,
    THORQ_PAYLOAD_FRIEND_EVENT_STATUS, ///< Online/Offline/Session (also sent when added)
    THORQ_PAYLOAD_FRIEND_EVENT_REMOVED ///< Friend removed
};

#endif // THORQ_PAYLOAD_RELATION_H
