#ifndef THORQ_PAYLOAD_SESSION_H
#define THORQ_PAYLOAD_SESSION_H

#include "thorq_payload.h"

typedef enum {
	THORQ_CMD_SESSION_REQUEST,
	THORQ_CMD_SESSION_ACCEPT,
	THORQ_CMD_SESSION_DENY,
	THORQ_CMD_SESSION_LEAVE,
} thorq_cmd_session_t;

#endif // THORQ_PAYLOAD_SESSION_H
