include "uuid.fbs";
include "user.fbs";
include "file.fbs";

namespace ThorQ.Serialization.Account;

struct AuthToken {
  token : [ ubyte : 64 ];
}
struct HashingSalt {
  salt : [ ubyte : 16 ];
}
struct HashingParameters {
  ops_limit : ulong;
  mem_limit : ulong;
  algorithm : int;
}
struct HashCalculated {
  hash : [ ubyte : 32 ];
}
struct HashNew {
  hash : [ ubyte : 32 ];
  salt : [ ubyte : 16 ];
  ops_limit : ulong;
  mem_limit : ulong;
  algorithm : int;
}

table GetAccountId {
  username : string;
}

table GetHashingSalt {
  account_id : Uuid;
  new_password : bool;
}

table GetNewHashingSalt {
  account_id : Uuid;
}

table GetHashingParameters {
  account_id : Uuid;
}

table LoginRequest {
  account_id : Uuid;
  password_hash : Account.HashCalculated;
  get_auth_token : bool;
}
table LoginResponse {
  success : bool;
  account_id : Uuid;
  auth_token : Account.AuthToken;
}

table LogoutRequest {
  logout_all : bool;
}
table LogoutResponse {
  success : bool;
}

table RegistrationRequest {
  account_id : Uuid;
  email : string;
  password_hash : Account.HashNew;
}
table RegistrationResponse {
  success : bool;
  account_id : Uuid;
}

table RecoveryRequest {
  email : string;
}
table RecoveryResponse {
  success : bool;
}

table DeletionRequest {
  password_hash : Account.HashCalculated;
}
table DeletionResponse {
  success : bool;
}

table UpdateRequest {
  old_password : Account.HashCalculated;
  new_username : string;
  new_password : Account.HashNew;
  new_email : string;
}
table UpdateResponse {
  success : bool;
}

table SetImageRequest {
  new_image : [ ubyte ];
}
table SetImageResponse {
  success : bool;
}

struct GetImageRequest {
  user_id : Uuid;
}
table GetImageResponse {
  image_id : Uuid;
}

/// Yada, yada...
union Body {
  get_account_id : Account.GetAccountId,
  account_id : Uuid,

  get_hashing_salt : Account.GetHashingSalt,
  hashing_salt : Account.HashingSalt,

  get_hashing_parameters : Account.GetHashingParameters,
  hashing_parameters : Account.HashingParameters,

  login_request : Account.LoginRequest,
  login_response : Account.LoginResponse,

  logout_request : Account.LogoutRequest,
  logout_response : Account.LogoutResponse,

  registration_request : Account.RegistrationRequest,
  registration_response : Account.RegistrationResponse,

  recovery_request : Account.RecoveryRequest,
  recovery_response : Account.RecoveryResponse,

  deletion_request : Account.DeletionRequest,
  deletion_response : Account.DeletionResponse,

  update_request : Account.UpdateRequest,
  update_response : Account.UpdateResponse,

  set_image_request : Account.SetImageRequest,
  set_image_response : Account.SetImageResponse,

  get_image_request : Account.GetImageRequest,
  get_image_response : Account.GetImageResponse
}

table Message {
  body : Account.Body;
}
