include "uuid.fbs";
include "user.fbs";
include "file.fbs";

namespace ThorQ.Serialization.Account;

struct AuthToken {
  token : [ ubyte : 64 ];
}
struct HashingParameters {
  salt : [ ubyte : 16 ];
  ops_limit : ulong;
  mem_limit : ulong;
  algorithm : int;
}
struct HashCalculated {
  hash : [ ubyte : 32 ];
}
struct HashNew {
  hash : [ ubyte : 32 ];
  params : Account.HashingParameters;
}

table GetAccountId {
  username : string;
}

table GetHashingParameters {
  account_id : Uuid;
}

table GetAuthToken {
  user_id : Uuid;
  password_hash : Account.HashCalculated;
}

table Login {
  user_id : Uuid;
  auth_token : Account.AuthToken;
}

table Register {
  user_id : Uuid;
  email : string;
  password_hash : Account.HashNew;
}

table Recover {
  email : string;
}

table Delete {
  password_hash : Account.HashCalculated;
}

table Logout {
  logout_all : bool;
}

table SetUsername {
  username : string;
  password_hash : Account.HashCalculated;
}

table SetPassword {
  new_password_hash : Account.HashNew;
}

table SetEmail {
  email : string;
  password_hash : Account.HashCalculated;
}

table SetImage {
  image : [ ubyte ];
}

/// Yada, yada...
union Body {
  get_account_id : Account.GetAccountId,
  account_id : Uuid,

  get_hashing_parameters : Account.GetHashingParameters,
  hashing_parameters : Account.HashingParameters,

  get_auth_token : Account.GetAuthToken,
  auth_token : Account.AuthToken,

  login : Account.Login,
  register : Account.Register,
  recover : Account.Recover,
  delete : Account.Delete,
  logout : Account.Logout,

  set_username : Account.SetUsername,
  set_password : Account.SetPassword,
  set_email : Account.SetEmail,
  set_image : Account.SetImage
}

table Message {
  body : Account.Body;
}
