include "uuid.fbs";
include "user.fbs";
include "file.fbs";

namespace ThorQ.Serialization.Account;

struct AuthToken {
  token : [ ubyte : 64 ];
}
struct PasswordSeed {
  seed : [ ubyte : 32 ];
}

table GetAccount {
  username : string;
}

table Account {
  user_id : Uuid;
  password_seed : Account.PasswordSeed;
}

table GetAuthToken {
  user_id : Uuid;
  password_hash : string;
}

struct Login {
  user_id : Uuid;
  auth_token : Account.AuthToken;
}

table Register {
  user_id : Uuid;
  email : string;
  password_hash : string;
}

table Recover {
  email : string;
}

table Delete {
  password_hash : string;
}

table Logout {
  logout_all : bool;
}

table SetUsername {
  username : string;
  password_hash : string;
}

/// Sent from client to server to ask server to generate a new password seed for a new password
table GeneratePasswordSeed {
  password_hash : string;
}
/// Sent from server to client when seed has been generated
table PasswordSeedGenerated {
  password_seed : Account.PasswordSeed;
}
/// Sent from client to server after hash has been generated with seed
table SetPassword {
  new_password_hash : string;
}

table SetEmail {
  email : string;
  password_hash : string;
}

table SetImage {
  image : File.Image;
}

/// Yada, yada...
union Body {
  get_account : Account.GetAccount,
  account : Account.Account,
  get_auth_token : Account.GetAuthToken,
  login : Account.Login,
  register : Account.Register,
  recover : Account.Recover,
  delete : Account.Delete,
  logout : Account.Logout,
  generate_seed : Account.GeneratePasswordSeed,
  seed_generated : Account.PasswordSeedGenerated,
  set_username : Account.SetUsername,
  set_password : Account.SetPassword,
  set_email : Account.SetEmail,
  set_image : Account.SetImage
}

table Message {
  body : Account.Body;
}
