include  "uuid.fbs";

namespace ThorQ.Serialization.FriendRequest;

/// Yada, yada...
union Body {
  /// [REQ] Send friend request
  request : string,

  /// [OBJ] Pending incoming request
  incoming : Uuid,
  /// [REQ] Accept incoming friend request
  incoming_accept : Uuid,
  /// [REQ] Deny incoming friend request
  incoming_deny : Uuid,

  /// [OBJ] Pending outgoing request
  outgoing : Uuid,
  /// [REQ] Remove outgoing friend request
  outgoing_remove : Uuid,

  /// [SIG] Incoming/Outgoing request was accepted
  accepted : Uuid,

  /// [SIG] Incoming/Outgoing request was removed
  removed : Uuid
}

table Message {
  body : FriendRequest.Body;
}
