include "account.fbs";
include "announcement.fbs";
include "device.fbs";
include "crypto.fbs";
include "file.fbs";
include "friendrequest.fbs";
include "group.fbs";
include "moderation.fbs";
include "systemid.fbs";
include "user.fbs";
include "version.fbs";
include "p2p.fbs";

namespace ThorQ.Serialization;

union Body {
  account : Account.Message,
  announcement : Announcement.Message,
  device : Device.Message,
  crypto : Crypto.Message,
  file : File.Message,
  friend_request : FriendRequest.Message,
  group : Group.Message,
  moderation : Moderation.Message,
  system_id : SystemId.Message,
  user : User.Message,
  version : Version,
  p2p : Peer2Peer.Message
}

table Message {
  body : Serialization.Body;
}

table MessageBuffer {
  body : [ Serialization.Message ];
}

root_type Message;
