include "account.fbs";
include "announcement.fbs";
include "crypto.fbs";
include "files.fbs";
include "heartbeat.fbs";
include "moderation.fbs";
include "group.fbs";
include "systemid.fbs";
include "uuid.fbs";
include "version.fbs";

namespace ThorQ.Serialization;

union Body {
  version : Version,
  heartbeat : Heartbeat,
  account : Account.Message,
  announcement : Announcement,
  crypto : Crypto.Message,
  moderation : Moderation.Message,
}

table Message {
  body : Serialization.Body;
}

table MessageBuffer {
  messages : [ Serialization.Message ];
}

root_type Message;
