include  "uuid.fbs";

namespace ThorQ.Serialization.Relationship;

enum Status : ubyte
{
  Blocked,
  None,
  Pending,
  Friend
}

enum Authority : ubyte
{
  Silent,
  Notify,
  Accept,
  Exclusive
}

table Relationship {
  /// public id of the relationship
  uuid:Uuid;
  
  /// Relationship status
  status:Status;
  
  /// Actions to be taken on session requested
  authority:Authority;
  
  /// Name of user these apply to
  username:string;
}

table Session {
  uuid:Uuid;
  icon:Uuid;
  name:string;
  members:[Uuid];
}
