include  "uuid.fbs";

namespace ThorQ.Serialization.User;

enum Presence : ubyte {
  Offline,
  Idle,
  Online
}

enum Friendship : ubyte {
  Friend,
  Favorite
}

enum Authority : ubyte {
  None,
  Moderator,
  Administrator,
  Founder
}

table User {
  /// public id of the user
  uuid : Uuid;

  /// Name of user
  name : string;

  /// Profile picture of user
  image_id : Uuid;

  /// User presence
  presence : User.Presence;

  /// User authorities
  authority : [ User.Authority ];

  /// Devices online right now (Collar/Toy/etc...)
  devices : [ Uuid ];
}

table UserOther {
  user : User.User;
  nickname : string;
  friendship : User.Friendship;
  is_muted : bool;
  is_blocked : bool;
  auto_accept : bool;
  notify_online : bool;
}

table UserSelf {
  user : User.User;
  email : string;
  relationships : [ Uuid ];
  friendrequests_outgoing : [ Uuid ];
  friendrequests_incoming : [ Uuid ];
}

table GetUser {
  user_id : Uuid;
}

/// Yada, yada...
union Body {
  user : User.User,
  get : Uuid,
  block : Uuid,
  unblock : Uuid
}

table Message {
  body : User.Body;
}
