include  "uuid.fbs";

namespace ThorQ.Serialization.User;

enum Friendship : ubyte {
  None,
  Friend,
  Favorite
}

table User {
  /// public id of the user
  uuid : Uuid;

  /// Name of user
  name : string;

  /// Profile picture of user
  image_id : Uuid;
}
table UserOther {
  user : User.User;
  friendship : User.Friendship;
  is_blocked : bool;
}

table UserSelf {
  user : User.User;
  email : string;
  relationships : [ User.UserOther ];
}

/// Yada, yada...
union Body {
  user : User.User,
  get : Uuid,
  block : Uuid,
  unblock : Uuid
}

table Message {
  body : User.Body;
}



