name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          install-deps: 'true'
          modules: 'qtcore qtgui qtopengl qtwidgets qtserialport qtconcurrent qtsql'
      - name: Install apt packages
        run: |
          sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa |
          sudo apt update -qq |
          sudo apt install libssl-dev
