name: CI

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ master, develop ]
jobs:
    setup:
        steps:
            - name: Check out repository
                uses: actions/checkout@v2
                with:
                    submodules: true
            - name: Set up python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9.0'
            - name: Set up Qt
                uses: jurplel/install-qt-action@v2
                with:
                    install-deps: 'true'
                    modules: 'qtcore qtgui qtopengl qtwidgets qtserialport qtconcurrent qtsql'
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Install apt packages
                run: |
                    sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa |
                    sudo apt update -qq |
                    sudo apt install libssl-dev
//    setup-windows-latest:
//        needs: setup
//        runs-on: windows-latest
//        steps:
